<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('report_confirmations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('report_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();
            // UUID generated by the browser and stored in localStorage
            $table->string('guest_token', 36);
            $table->enum('vote', ['still_here', 'no_longer_here']);
            $table->timestamps();

            // Prevent the same browser from voting twice on the same report
            $table->index(['report_id', 'guest_token']);
            $table->index(['report_id', 'user_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('report_confirmations');
    }
};
